Update ssa.yml

diff --git a/.github/workflows/ssa.yml b/.github/workflows/ssa.yml
--- a/.github/workflows/ssa.yml
+++ b/.github/workflows/ssa.yml
@@ -62,16 +62,16 @@ jobs:
         # Copy Ass 1 2 3 Cpp version
         for i in {1..3}; do
           echo "Copying Assignment-$i..."
-          if ! cp "solutions/Assignment-$i/CPP/Assignment-$i.cpp" "teaching/Assignment-$i/CPP/Assignment-$i.cpp"; then
-            echo "Failed to copy Assignment-$i CPP"
+          if ! cp "solutions/Assignment-$i/CPP/Assignment_$i.cpp" "teaching/Assignment-$i/CPP/Assignment_$i.cpp"; then
+            echo "Failed to copy Assignment_$i CPP"
             exit 1
           fi
         done
         # Copy Ass 1 2 3 Python Version
         for i in {1..3}; do
           echo "Copying Assignment-$i..."
-          if ! cp "solutions/Assignment-$i/Python/Assignment$i.py" "teaching/Assignment-$i/Python/Assignment$i.py"; then
-            echo "Failed to copy Assignment-$i Python"
+          if ! cp "solutions/Assignment-$i/Python/Assignment_$i.py" "teaching/Assignment-$i/Python/Assignment_$i.py"; then
+            echo "Failed to copy Assignment_$i Python"
             exit 1
           fi
         done
