Update ssa.yml

diff --git a/.github/workflows/ssa.yml b/.github/workflows/ssa.yml
--- a/.github/workflows/ssa.yml
+++ b/.github/workflows/ssa.yml
@@ -25,8 +25,8 @@ jobs:
       with:
         repository: 'yuleisui/Software-Security-Analysis'
         path: 'solutions'
-        token: ${{ secrets.TEACHING_CI }}
-        
+        token: ${{ secrets.SOLUTIONS_PAT }}
+
     - uses: actions/setup-node@v3
       with:
         node-version: 18
@@ -44,16 +44,39 @@ jobs:
       run: |
         npm install svf-lib
 
+    # set python version
+    - name: Set up Python 3.10
+      uses: actions/setup-python@v4
+      with:
+        python-version: '3.10'
+
+    - name: Install Python dependencies
+      run: |
+        pip install --upgrade pip
+        pip install wheel pybind11 notebook nbconvert nbclient ipykernel build z3-solver
+        pip install pysvf -i https://test.pypi.org/simple/
+
     - name: Replace assignments with solutions
       run: |
         set -e  
+        # Copy Ass 1 2 3 Cpp version
         for i in {1..3}; do
           echo "Copying Assignment-$i..."
-          if ! cp "solutions/Assignment-$i/Assignment-$i.cpp" "teaching/Assignment-$i/Assignment-$i.cpp"; then
-            echo "Failed to copy Assignment-$i"
+          if ! cp "solutions/Assignment-$i/CPP/Assignment-$i.cpp" "teaching/Assignment-$i/CPP/Assignment-$i.cpp"; then
+            echo "Failed to copy Assignment-$i CPP"
             exit 1
           fi
         done
+        # Copy Ass 1 2 3 Python Version
+        for i in {1..3}; do
+          echo "Copying Assignment-$i..."
+          if ! cp "solutions/Assignment-$i/Python/Assignment$i.py" "teaching/Assignment-$i/Python/Assignment$i.py"; then
+            echo "Failed to copy Assignment-$i Python"
+            exit 1
+          fi
+        done
+
+        
         # Copy Lab-Exercise1 2 3
         cp -r solutions/Lab-Exercise-1/GraphAlgorithm.cpp teaching/Lab-Exercise-1/GraphAlgorithm.cpp
         cp -r solutions/Lab-Exercise-2/Z3Examples.cpp teaching/Lab-Exercise-2/Z3Examples.cpp
